#server:
#  port: 8080
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger
#
#spring:
#
##    console:
##      enabled: true
##    path: /h2-console
#  datasource:
#    url: jdbc:mysql://localhost:3306/test7
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#
#  jpa:
#    database-platform: rg.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#
#    repositories:
#      enable: true
#
#    show-sql: true



